# Generated by Django 5.1.4 on 2024-12-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="face_recognition_threshold",
            field=models.FloatField(default=0.6),
        ),
    ]
