# Generated by Django 5.1.4 on 2024-12-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("users", "0003_profile_face_embedding_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="name",
        ),
        migrations.AddField(
            model_name="attendance",
            name="department",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
    ]
