# Generated by Django 5.1.4 on 2024-12-25 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="department_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="attendance",
            name="fullname",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="attendance",
            name="percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
