# Generated by Django 5.1.4 on 2024-12-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendance_department_name_attendance_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
