# Generated by Django 5.1.4 on 2024-12-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendance_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="percentage",
        ),
    ]
