# Generated by Django 5.1.4 on 2024-12-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remove_attendance_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="time",
            new_name="check_in_time",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
