# Generated by Django 5.1.4 on 2024-12-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_rename_time_attendance_check_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Half present", "Half present"),
                    ("Absent", "Absent"),
                ],
                max_length=20,
            ),
        ),
    ]
