# Generated by Django 5.1.4 on 2024-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_attendance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="late",
            field=models.BooleanField(default=False),
        ),
    ]
