# Generated by Django 5.1.4 on 2024-12-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_attendance_late"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
