# Generated by Django 5.1.4 on 2024-12-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_alter_attendance_check_in_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
